### ISSUE TITLE
Release to fez and remove from p6c

### ISSUE THREAD

**Issue by 2colours** [grondilu/finite-fields-raku#8]
Hi,

from what I can see, currently, this module is available both in the "zef ecosystem" and p6c - however, the p6c version is more up-to-date. Please make releases using fez and then this repository can be removed from the old master list which is really a legacy thing.

Thank you.

**Comment by grondilu** [comment]
I've just successfully uploaded with fez, but I don't remember what p6c is.

**Comment by 2colours** [comment]
For all intents and purposes, [this humongous text file](https://github.com/Raku/ecosystem/edit/main/META.list) is p6c. The dependency managers would simply examine the META files to resolve dependencies.

It was pretty obvious from early on that this is not going to scale, it's not really sufficient for versioning or integrity checks. This first led to setting up a CPAN infrastructure for Perl 6/Raku and then the creation of the "zef ecosystem" (which is quite a dysfunctional name but oh well). 

The goal would be to eventually move away from p6c (and CPAN as well but that's a much more isolated thing) - all your concern should be this PR that I opened. https://github.com/Raku/ecosystem/pull/625 If this repository gets removed, it means that it won't keep popping up in raku.land and one won't retrieve it implicitly from the git repo's HEAD. Of course, people will still be able to _explicitly_ install from the content of your repo but not because of any central ecosystem.

Instead, you will be able to (and have to, at the same time) release your code using `fez`. The versions you explicitly upload, with the metadata you set, will be authoritative, over whatever the git repo has.

**Comment by 2colours** [comment]
I think this can be closed, I just wanted to give it some time, "to sink in". :)
